Validate contact form
Danfall369/Microverse-Portfolio pull request #17
Opened 2023-03-10 16:59 UTC by Danfall369

we include a client-side validation to catch and throw errors in the UI.
-when the user doesn't write anything in the forms and clicks on the submit button, messages appear to notify a name and email are required.
-when the user writes an upper-case email. a message appears to notify then The content of the email field has to be in lowercase.

2023-03-10 17:26 UTC, christianbiring1 requested changes
Hi @Danfall369 @VelzckC0D3 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# STATUS: REQUEST CHANGES :recycle: 
![almost](https://user-images.githubusercontent.com/97100091/224382424-d3541893-ed0d-4d28-b1d6-2b1cd53e2ef0.gif)


## Highlights
- [ ] All linters checks are green :heavy_check_mark: 
- [ ] Descriptive PR `title` and `summary`
- [ ] Git-flow is used correctly :+1: 
- [ ] Professional README 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-10 17:26 UTC, christianbiring1 commented on js/projectcode.js
> +  validateInputs();
- [ ] As you may notice here, no matter how the input state is, the form will always be prevented for submission, kindly fix that.

`Hint: YOu may consider preventing the form where an error is present.`

2023-03-10 20:16 UTC, BenMukebo requested changes
Hi @TEAM,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight :clap: 
- GitHub flow is followed. :heavy_check_mark:


 ## Required Changes ♻️
_Check the comments under the review._

You have submitted a project, that Linters check are not running in the GitHub/action
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please Tag me on (@BenMukebo) when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-10 20:16 UTC, BenMukebo commented on js/projectcode.js
> +  }
- [ ] According to the project requirements, The contact form should contain at least one validation checking if the email is written in all lowercase:
* If a user submits the contact form with the email field containing uppercase characters an error message should show up.
* If a user submits the contact form with the email field containing only lowercase characters the form is sent normally.

- Actually, I can submit the form even if the email input field contains one or two Uppercase characters. Please address this. 💯 👍🏻 

- Note Your app should check if the email is all lowercase by comparing if the email and it's lowercase converted version are the same, ie: `email === email.toLowerCase()`, utilizing regular expressions, or looping through each letter of the email string.

2023-03-10 23:40 UTC, Danfall369 commented on js/projectcode.js
> +  }
@BenMukebo please, I have only one more code review, cant you help me on slack or zoom to make the changes correctly? ill fix the thing on the Lower Case, but I don't know if I'll have more problems

2023-03-11 03:07 UTC, didierganthier approved these changes
Hi Team,

Congratulations! 🎉 Your project is complete and ready to be merged! 🚀

<img src="https://media.giphy.com/media/l9CSJHK88kMTe/giphy.gif" />

## Highlights
- Descriptive PR ✔️ 
- Linters passing ✔️ 
- Correct GitHub flow ✔️ 

## Optional Suggestions 💡
- While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really enhance your application.

Cheers and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Once again, congratulations on completing this project! 🎉

2023-03-11 03:07 UTC, didierganthier commented on js/projectcode.js
> +    messageEmail.classList.add('error');
[OPTIONAL] Well done on showing the right error in case the email is not fully lowercase 👍🏽 but it could use some styling. This is what you have for now 👇🏽 

![Screenshot 2023-03-10 at 22 04 34](https://user-images.githubusercontent.com/45739963/224461663-b432488f-2be0-4afc-bdd3-b0adab6fcc69.png)

I'd suggest red and smaller. 😉

2023-03-11 03:07 UTC, didierganthier commented on js/projectcode.js
> +});
[OPTIONAL] Nice work 💯 but for now your code is a bit messy, look to improve that by using several `js` files to handle different functionalities. 😉

2023-03-11 03:11 UTC, merged