Pair programming branch
Danfall369/Microverse-Portfolio pull request #5
Opened 2023-02-22 16:39 UTC by Danfall369

-add the "form" section in the index.html
-add values to Style.css to the Form section
-change the image on the bout me section and replace it with bubbles text
-fix the green buttons
-some fixes to improve a more clean code.

2023-02-22 18:41 UTC, joel-kalema requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hello Team
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me @joel-kalema  when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-22 18:41 UTC, joel-kalema commented on index.html
> +          </fieldset>
Hello Team, good job so far 😃, as I can see, your project is running, but you need to fix some parts

- [ ] Kindly, make sure your `<textarea>` has a `required` attribute to activate the validation on submit 👍

2023-02-22 18:41 UTC, joel-kalema commented on README.md
> +# 📖 Portfolio Project <a name="about-project"></a>
- [ ] Good job team 😃.  It could be better if you add some information about your partner because he contributed to your project and just to make your README professional 👍

2023-02-22 19:04 UTC, Danfall369 commented on index.html
> +          </fieldset>
@joel-kalema done!

2023-02-22 19:05 UTC, Danfall369 commented on README.md
> +# 📖 Portfolio Project <a name="about-project"></a>
@joel-kalema deal! I include him in the Authors section

2023-02-22 19:17 UTC, frank1738 approved these changes
Hi @Danfall369 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/J8FZIm9VoBU6Q/giphy.gif"/>

## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ Form submission is working properly👍 


## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-22 19:19 UTC, merged

2023-02-23 10:35 UTC, joel-kalema commented on index.html
> +          </fieldset>
well